export const sample_products = [
  {
    id: "1",
    name: "Jasmine Rice",
    price: 50,
    originCountry: ["Japan"],
    imageUrl: "jasmineRice.jpg",
    tags: ["Food", "Rice", "Daily Products"],
  },
  {
    id: "2",
    name: "Sushi Rice",
    price: 39,
    originCountry: ["China"],
    imageUrl: "sushiRice.jpg",
    tags: ["Food", "Rice", "Daily Products"],
  },
  {
    id: "3",
    name: "Hot Pot",
    price: 700,
    originCountry: ["Taiwan"],
    imageUrl: "hotPot.jpg",
    tags: ["Kitchen Equipment"],
  },
  {
    id: "4",
    name: "Korean Grill",
    price: 439,
    originCountry: ["South Korea"],
    imageUrl: "koreanGrill.jpg",
    tags: ["Kitchen Equipment"],
  },
  {
    id: "5",
    name: "Instant noodles with beef",
    price: 9,
    originCountry: ["Japan"],
    imageUrl: "beefNoodles.jpg",
    tags: ["Fast food", "Noodles", "Daily Products"],
  },
  {
    id: "6",
    name: " Spicy instant noodles",
    price: 9,
    originCountry: ["Japan"],
    imageUrl: "spicyNoodles.jpg",
    tags: ["Fast food", "Noodles", "Daily Products"],
  },
  {
    id: "7",
    name: " Mango buble tea",
    price: 29,
    originCountry: ["China"],
    imageUrl: "mangoTea.jpg",
    tags: ["Drinks", "Tea", "Daily Products"],
  },
  {
    id: "8",
    name: "Ramune lemonade",
    price: 19,
    originCountry: ["China"],
    imageUrl: "ramuneDrink.jpg",
    tags: ["Drinks", "Lemonade", "Daily Products"],
  },
];

export const sample_tags = [
  { name: 'All' },
  { name: 'Food' },
  { name: 'Drinks' },
  { name: 'Kitchen Equipment' },
  { name: 'Daily Products' },
  { name: 'Rice' },
  { name: 'Fast food' },
  { name: 'Noodles' },
  { name: 'Tea' },
  { name: 'Lemonade' },
];

export const sample_users = [
  {
    id: 1,
    name: 'Domantas',
    email: 'domantas@gmail.com',
    password: '12345',
    address: 'Copenhagen',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Domantas J',
    email: 'domantasj@gmail.com',
    password: '123456',
    address: 'Naerum',
    isAdmin: true,
  },
];
